name: 密钥扫描

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**/*.py"
  pull_request:
    branches:
      - main
    paths:
      - "**/*.py"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 加固运行器（审计所有出站调用）
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - name: 检出代码
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: 密钥扫描
        uses: trufflesecurity/trufflehog@4158734f234bd8770128deae2e2975cfab4b66a6 # main
        with:
          extra_args: --results=verified,unknown
